import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import {
  absoluteFromRootHref,
  BEHAVIOR_SCOPE_MODULE_HREF,
  CORE_BUNDLE_HREF,
  listBehaviorScopeBundles,
  listBehaviorScopeKeys,
  listBundleTargets,
  parseStyleImports,
  readStyleCoreImports,
  relativeBundleOutput,
  type CssImportRef,
} from './css-manifest.mjs';
import { toPosixPath } from './shared/build-topology.mjs';

const ROOT_DIR = path.resolve(import.meta.dirname, '..', '..');
const BUNDLE_HEADER = '/* Generated by scripts/css-bundle.mjs — do not edit by hand. */\n';
const RUNTIME_SCOPE_HEADER = '// Generated by scripts/css-bundle.mjs - do not edit by hand.\n';

type FlattenOptions = {
  includeExternalImports?: boolean;
};

function stripSourceMapComments(source: string): string {
  return source.replace(/\/\*#\s*sourceMappingURL=[^*]*\*\/\s*/gu, '');
}

function normalizeCssBody(source: string): string {
  return stripSourceMapComments(source)
    .split('\n')
    .map((line) => line.replace(/\s+$/u, ''))
    .join('\n')
    .trim();
}

function stripManifestAndImports(source: string): string {
  return normalizeCssBody(
    source
      .replace(/^@layer\s+[^;]+;\s*/m, '')
      .replace(/@import\s+url\((['"]?)([^'")]+)\1\)\s*(?:layer\(([^)]+)\))?\s*;/g, ''),
  );
}

async function readLocalCss(href: string): Promise<string> {
  const absolutePath = absoluteFromRootHref(href);
  return fs.readFile(absolutePath, 'utf8');
}

async function readTextIfExists(absolutePath: string): Promise<string | null> {
  try {
    return await fs.readFile(absolutePath, 'utf8');
  } catch (error: any) {
    if (error?.code === 'ENOENT') return null;
    throw error;
  }
}

async function flattenImportList(
  imports: CssImportRef[],
  seen = new Set<string>(),
  options: FlattenOptions = {},
): Promise<string> {
  const externalLines: string[] = [];
  const chunks: string[] = [];

  for (const entry of imports) {
    if (entry.external) {
      if (options.includeExternalImports !== false) {
        externalLines.push(`@import url("${entry.file}");`);
      }
      continue;
    }

    if (seen.has(entry.file)) continue;
    seen.add(entry.file);

    const raw = await readLocalCss(entry.file);
    const nestedImports = parseStyleImports(raw);
    let body = stripManifestAndImports(raw);

    if (nestedImports.length) {
      const nestedBody = await flattenImportList(nestedImports, seen, options);
      body = `${body}\n\n${nestedBody}`.trim();
    }

    const wrapped = entry.layer ? `@layer ${entry.layer} {\n${body}\n}` : body;
    chunks.push(`/* ${entry.file} */\n${wrapped}`);
  }

  return [...externalLines, ...chunks].filter(Boolean).join('\n\n');
}

function layerForScopedFile(file: string, kind: 'route' | 'behavior'): string {
  if (kind === 'route') return 'routes';
  if (file.includes('/components/')) return 'components';
  if (file.includes('/handles/')) return 'handles';
  if (file.includes('/effects/')) return 'effects';
  if (file.includes('/ornament/')) return 'ornament';
  return 'systems';
}

async function flattenExplicitFiles(
  files: string[],
  kind: 'route' | 'behavior',
): Promise<string> {
  const chunks: string[] = [];

  for (const file of files) {
    const raw = await readLocalCss(file);
    const body = stripManifestAndImports(raw);
    const layer = layerForScopedFile(file, kind);
    const wrapped = `@layer ${layer} {\n${body}\n}`;
    chunks.push(`/* ${file} */\n${wrapped}`);
  }

  return chunks.join('\n\n');
}

export async function buildCssBundles(options: { check?: boolean } = {}): Promise<Array<{
  href: string;
  bytes: number;
  written: boolean;
}>> {
  const targets = listBundleTargets();
  const coreImports = await readStyleCoreImports();
  const results: Array<{ href: string; bytes: number; written: boolean }> = [];

  for (const target of targets) {
    const flattened = target.kind === 'core'
      ? await flattenImportList(coreImports)
      : await flattenExplicitFiles(target.files, target.kind);

    const output = `${BUNDLE_HEADER}${flattened}${flattened.endsWith('\n') ? '' : '\n'}`;
    const outputPath = absoluteFromRootHref(target.href);

    await fs.mkdir(path.dirname(outputPath), { recursive: true });

    let current: string | null = null;
    try {
      current = await fs.readFile(outputPath, 'utf8');
    } catch (error: any) {
      if (error?.code !== 'ENOENT') throw error;
    }

    const isFresh = current === output;
    if (options.check && !isFresh) {
      throw new Error(`[css-bundle] stale output: ${relativeBundleOutput(target.href)}`);
    }

    if (!options.check && !isFresh) {
      await fs.writeFile(outputPath, output, 'utf8');
    }

    results.push({
      href: target.href,
      bytes: Buffer.byteLength(output, 'utf8'),
      written: !options.check && !isFresh,
    });
  }

  return results;
}

function renderBehaviorScopeModule(): string {
  const keys = listBehaviorScopeKeys();
  const bundles = listBehaviorScopeBundles();
  const keyLines = keys.map((key) => `  '${key}',`).join('\n');
  const bundleLines = Object.entries(bundles)
    .map(([key, href]) => `  '${key}': '${href}',`)
    .join('\n');

  return `${RUNTIME_SCOPE_HEADER}/**
 * Behavior feature keys generated from scripts/ts/css-manifest.mts BEHAVIOR_SCOPES.
 * Each key gates a CSS behavior bundle via body[data-spw-features~="..."].
 */

export const BEHAVIOR_SCOPE_KEYS = Object.freeze([
${keyLines}
]);

export const BEHAVIOR_SCOPE_BUNDLES = Object.freeze({
${bundleLines}
});

export const SPW_BEHAVIOR_SCOPES_CONTRACT = Object.freeze({
  keys: BEHAVIOR_SCOPE_KEYS,
  bundles: BEHAVIOR_SCOPE_BUNDLES,
  portableUse:
    'Use matchesFeatures() with module def.features to align runtime mounts with scoped CSS behavior bundles.',
});
`;
}

export async function buildBehaviorScopeModule(options: { check?: boolean } = {}): Promise<{
  href: string;
  bytes: number;
  written: boolean;
}> {
  const output = renderBehaviorScopeModule();
  const outputPath = absoluteFromRootHref(BEHAVIOR_SCOPE_MODULE_HREF);
  const current = await readTextIfExists(outputPath);
  const isFresh = current === output;

  if (options.check && !isFresh) {
    throw new Error(`[css-bundle] stale output: ${relativeBundleOutput(BEHAVIOR_SCOPE_MODULE_HREF)}`);
  }

  if (!options.check && !isFresh) {
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, output, 'utf8');
  }

  return {
    href: BEHAVIOR_SCOPE_MODULE_HREF,
    bytes: Buffer.byteLength(output, 'utf8'),
    written: !options.check && !isFresh,
  };
}

export async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const results = await buildCssBundles({ check });
  const behaviorScopeResult = await buildBehaviorScopeModule({ check });
  const verb = check ? 'checked' : 'built';

  console.log(`[css-bundle] ${verb} ${results.length} scoped stylesheet bundle(s)`);
  for (const result of results) {
    const suffix = check ? '' : result.written ? ' updated' : ' fresh';
    const label = result.href === CORE_BUNDLE_HREF ? 'core' : result.href;
    console.log(`  ${label}: ${(result.bytes / 1024).toFixed(1)} KiB${suffix}`);
  }
  console.log(`  runtime: ${behaviorScopeResult.href} (${(behaviorScopeResult.bytes / 1024).toFixed(1)} KiB)${check ? '' : behaviorScopeResult.written ? ' updated' : ' fresh'}`);
}

const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  await main();
}
